# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoHisto
                                 A QGIS plugin
 Création de BDD d'arvhives foncières
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-23
        copyright            : (C) 2023 by C. Blanc
        email                : c.blanc@2age.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoHisto class from file GeoHisto.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GeoHisto import GeoHisto
    return GeoHisto(iface)
